name: Deploy v86 to Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm install
      - name: Install Rust WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: make

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
